import type { PerfTraceProject } from '../types/projectSchema';

export const DEMO_PROJECT: PerfTraceProject = {
  version: '1.0',
  meta: {
    name: 'Arduino + 555 Pulse Generator',
    createdAt: '2026-09-30T10:00:00.000Z',
    savedAt: '2026-09-30T10:00:00.000Z',
  },
  board: {
    rows: 24,
    cols: 36,
  },
  components: [
    {
      id: 'comp-nano-1',
      name: 'A1',
      type: 'arduino_nano',
      position: { col: 6, row: 8 },
      orientation: 'horizontal',
      pinMap: {},
      value: 'Arduino Nano',
      locked: false,
    },
    {
      id: 'comp-555-1',
      name: 'U1',
      type: 'dip8',
      position: { col: 25, row: 6 },
      orientation: 'horizontal',
      pinMap: {},
      value: 'NE555 Timer',
      locked: false,
    },
    {
      id: 'comp-hdr-pwr',
      name: 'J1',
      type: 'header1x2',
      position: { col: 2, row: 4 },
      orientation: 'horizontal',
      pinMap: {},
      value: '5V / GND',
      locked: false,
    },
    {
      id: 'comp-hdr-i2c',
      name: 'J2',
      type: 'header1x4',
      position: { col: 12, row: 3 },
      orientation: 'horizontal',
      pinMap: {},
      value: 'I2C / UART',
      locked: false,
    },
    {
      id: 'comp-res-1',
      name: 'R1',
      type: 'resistor',
      position: { col: 25, row: 12 },
      orientation: 'horizontal',
      pinMap: {},
      value: '10kΩ',
      locked: false,
    },
    {
      id: 'comp-res-2',
      name: 'R2',
      type: 'resistor',
      position: { col: 25, row: 3 },
      orientation: 'horizontal',
      pinMap: {},
      value: '4.7kΩ',
      locked: false,
    },
    {
      id: 'comp-res-3',
      name: 'R3',
      type: 'resistor',
      position: { col: 29, row: 8 },
      orientation: 'horizontal',
      pinMap: {},
      value: '220Ω',
      locked: false,
    },
    {
      id: 'comp-res-4',
      name: 'R4',
      type: 'resistor',
      position: { col: 6, row: 4 },
      orientation: 'horizontal',
      pinMap: {},
      value: '10kΩ',
      locked: false,
    },
    {
      id: 'comp-cap-1',
      name: 'C1',
      type: 'capacitor',
      position: { col: 30, row: 3 },
      orientation: 'horizontal',
      pinMap: {},
      value: '10µF',
      locked: false,
    },
    {
      id: 'comp-cap-2',
      name: 'C2',
      type: 'capacitor',
      position: { col: 25, row: 15 },
      orientation: 'horizontal',
      pinMap: {},
      value: '100nF',
      locked: false,
    },
    {
      id: 'comp-cap-3',
      name: 'C3',
      type: 'capacitor',
      position: { col: 2, row: 7 },
      orientation: 'horizontal',
      pinMap: {},
      value: '100nF',
      locked: false,
    },
    {
      id: 'comp-led-1',
      name: 'D1',
      type: 'led',
      position: { col: 31, row: 11 },
      orientation: 'horizontal',
      pinMap: {},
      value: 'Pulse LED',
      locked: false,
    },
    {
      id: 'comp-led-2',
      name: 'D2',
      type: 'led',
      position: { col: 2, row: 11 },
      orientation: 'horizontal',
      pinMap: {},
      value: 'Power LED',
      locked: false,
    },
    {
      id: 'comp-to92-1',
      name: 'Q1',
      type: 'to92',
      position: { col: 29, row: 15 },
      orientation: 'horizontal',
      pinMap: {},
      value: '2N2222',
      locked: false,
    },
  ],
  traces: [
    // --- VCC Rail (Red) ---
    {
      id: 't-vcc-1',
      from: { col: 2, row: 4 },
      to: { col: 2, row: 2 },
      signalType: 'power',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-vcc-2',
      from: { col: 2, row: 2 },
      to: { col: 34, row: 2 },
      signalType: 'power',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-vcc-3',
      from: { col: 25, row: 2 },
      to: { col: 25, row: 3 },
      signalType: 'power',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-vcc-4',
      from: { col: 27, row: 3 },
      to: { col: 28, row: 6 }, // 555 Pin 8 VCC
      signalType: 'power',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-vcc-5',
      from: { col: 6, row: 2 },
      to: { col: 6, row: 4 },
      signalType: 'power',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-vcc-6',
      from: { col: 28, row: 2 },
      to: { col: 27, row: 6 }, // 555 Pin 4 Reset
      signalType: 'power',
      material: 'solder',
      locked: false,
    },

    // --- GND Rail (Ground) ---
    {
      id: 't-gnd-1',
      from: { col: 3, row: 4 },
      to: { col: 3, row: 21 },
      signalType: 'ground',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-gnd-2',
      from: { col: 3, row: 21 },
      to: { col: 34, row: 21 },
      signalType: 'ground',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-gnd-3',
      from: { col: 25, row: 8 }, // 555 Pin 1 GND
      to: { col: 25, row: 10 },
      signalType: 'ground',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-gnd-4',
      from: { col: 25, row: 10 },
      to: { col: 25, row: 21 },
      signalType: 'ground',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-gnd-5',
      from: { col: 32, row: 11 }, // LED D1 Cathode
      to: { col: 32, row: 21 },
      signalType: 'ground',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-gnd-6',
      from: { col: 3, row: 11 }, // LED D2 Cathode
      to: { col: 3, row: 13 },
      signalType: 'ground',
      material: 'solder',
      locked: false,
    },

    // --- Signals & Timing Traces (HF / LF) ---
    // 555 Trigger (Pin 2) to Threshold (Pin 6)
    {
      id: 't-sig-1',
      from: { col: 26, row: 8 },
      to: { col: 26, row: 6 },
      signalType: 'lf_data',
      material: 'solder',
      locked: false,
    },
    // 555 Output (Pin 3) to Resistor R3
    {
      id: 't-sig-2',
      from: { col: 27, row: 8 },
      to: { col: 29, row: 8 },
      signalType: 'hf_data',
      material: 'solder',
      locked: false,
    },
    // R3 to LED D1 Anode
    {
      id: 't-sig-3',
      from: { col: 31, row: 8 },
      to: { col: 31, row: 11 },
      signalType: 'lf_data',
      material: 'solder',
      locked: false,
    },
    // I2C SDA / SCL Traces to Nano
    {
      id: 't-i2c-1',
      from: { col: 13, row: 3 },
      to: { col: 13, row: 8 },
      signalType: 'hf_data',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-i2c-2',
      from: { col: 14, row: 3 },
      to: { col: 14, row: 8 },
      signalType: 'hf_data',
      material: 'solder',
      locked: false,
    },
    // Nano GPIO to R1
    {
      id: 't-gpio-1',
      from: { col: 20, row: 14 },
      to: { col: 23, row: 14 },
      signalType: 'lf_data',
      material: 'solder',
      locked: false,
    },
    {
      id: 't-gpio-2',
      from: { col: 23, row: 14 },
      to: { col: 25, row: 12 },
      signalType: 'lf_data',
      material: 'solder',
      locked: false,
    },

    // --- Arched Jumper Wires ---
    {
      id: 'jumper-1',
      from: { col: 20, row: 8 }, // Nano D2 pin
      to: { col: 27, row: 8 }, // 555 Output pin
      signalType: 'hf_data',
      material: 'wire',
      locked: false,
    },
    {
      id: 'jumper-2',
      from: { col: 8, row: 4 }, // Pullup R4
      to: { col: 8, row: 8 }, // Nano Reset
      signalType: 'lf_data',
      material: 'wire',
      locked: false,
    },
    {
      id: 'jumper-3',
      from: { col: 27, row: 12 }, // R1 output
      to: { col: 29, row: 15 }, // Transistor Base
      signalType: 'lf_data',
      material: 'wire',
      locked: false,
    },
  ],
  jumpers: [],
  nets: [],
};
